[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = firmware/src
include_dir = firmware/include
test_dir = firmware/test
data_dir = firmware/data

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -Werror=return-type
    -D DESKWAVE_VERSION=\"0.1.0\"

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs

[env:native]
platform = native@1.2.1
test_build_src = true
build_src_filter = -<main.cpp>
