[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = firmware/src
include_dir = firmware/include
test_dir = firmware/test
data_dir = firmware/data
lib_dir = firmware/lib

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -Werror=return-type
    -std=gnu++17
    -D DESKWAVE_VERSION=\"0.1.0\"
build_unflags =
    -std=gnu++11

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson@7.4.3
    links2004/WebSockets@2.7.3
    lovyan03/LovyanGFX@1.2.27
    bitbank2/JPEGDEC@1.8.4

[env:native]
platform = native@1.2.1
framework =
test_framework = unity
test_build_src = false
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror
